name: Build

on: [push, pull_request]

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Build
        run: go build ./...
